### PR TITLE
Add isovector

### PR DESCRIPTION
**Pull request by isovector**
Sorry about the line noise -- it was caused by my editor stripping trailing spaces.

### CODE REVIEW

**Comment by Wizek** [comment]
Hey, thanks for the PR, and welcome among us! 🙂

I don't mind your editor stripping away most trailing whitespace, but unfortunately some of those are significant and intentionally present for rendering. It's a markdown thing that newlines get merged unless there is 2 trailing whitespaces at the rear. Could you make sure that your changes keep the rendering the same of already present sections? E.g. [at this place](https://github.com/Wizek/haskell-pair-programming/pull/11/commits/2aded5ac1aca7a75c96dfdec3c2024cf273fff77?diff=split#diff-04c6e90faac2675aa89e2176d2eec7d8L39). All the trimming that keep the rendering I'm fine with.

**Comment by Wizek** [comment]
Oh, and I liked your post about HKD. 😉

**Comment by isovector** [comment]
[According to the rich diff](https://github.com/Wizek/haskell-pair-programming/pull/11/commits/2aded5ac1aca7a75c96dfdec3c2024cf273fff77?diff=split&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8), this doesn't affect any layout.

**Comment by Wizek** [comment]
Oh, quite right. I've forgot that I've 'refactored' that section to rely on `<ul>` since then. And the rich diff is a neat idea to confirm this too. I've [invited you](https://github.com/Wizek/haskell-pair-programming/invitations) as a collaborator, feel free to merge away.

**Comment by isovector** [comment]
great, thanks!

**Pull request merged**
