### PR TITLE
Add srid

### PR DESCRIPTION
**Pull request by srid**

### CODE REVIEW

**Comment by Wizek** [comment]
Sent you a collaborator invite, feel free to merge this yourself. :)

**Comment by srid** [comment]
Thanks :-) I haven't received the invite yet, but I'll check again in the evening.

**Comment by Wizek** [comment]
Oh, you actually have, you just don't know about it. :) For some reason GH doesn't notify users of these invites if they don't know where to look.

Look here: https://github.com/Wizek/haskell-pair-programming/invitations

**Comment by srid** [comment]
Ah, I see. That's weird UX from Github.

**Comment by Wizek** [comment]
Yes. I believe it's to prevent invite-spam, that happens on many other platforms, e.g. I remember seeing it on Twitter and Instagram.

**Pull request merged**
