### PR TITLE
Add kcsongor

### PR DESCRIPTION
**Pull request by kcsongor**
o/

### CODE REVIEW

**Comment by Wizek** [comment]
Welcome! Could you change the language flag to the US one? I'd like if we only used one per language (it's not intended to signify geographical location)

**Comment by kcsongor** [comment]
Ah, but it took so long to find! (sure, one sec)

**Comment by Wizek** [comment]
Great, thanks! Feel free to merge then :)

**Comment by kcsongor** [comment]
Thanks :)

**Pull request merged**
